### ISSUE TITLE
[4.12 upgrade] machine-config-operator pod crashlooping immediately after acquiring lease

### ISSUE THREAD

**Issue by solacelost** [okd-project/okd#1492]
**Describe the bug**
MCO itself is crashlooping after acquiring lease

<details>
  <summary>MCO pod logs</summary

```
I0204 22:47:50.743743       1 start.go:47] Version: 4.12.0-0.okd-2023-01-21-055900 (Raw: machine-config-daemon-4.6.0-202006240615.p0-1774-g60fb64fa-dirty, Hash: 60fb64fa861f1231f779226aa5dcd5c4ef604dcb)
I0204 22:47:50.751846       1 leaderelection.go:248] attempting to acquire leader lease openshift-machine-config-operator/machine-config...
I0204 22:50:33.294756       1 leaderelection.go:258] successfully acquired lease openshift-machine-config-operator/machine-config
I0204 22:50:33.905123       1 operator.go:276] Starting MachineConfigOperator
E0204 22:50:33.922907       1 runtime.go:79] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 268 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d70460?, 0xc0020d6408})
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000210070?})
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1d70460, 0xc0020d6408})
	/usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/openshift/machine-config-operator/pkg/operator.getIgnitionHost(0xc0005bdca0)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:366 +0x4f9
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncRenderConfig(0xc00014c240, 0x4bcc17?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:336 +0xe28
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncAll(0xc00014c240, {0xc0035c1d08, 0x6, 0x0?})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:115 +0x3b8
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).sync(0xc00014c240, {0xc0004f4c30, 0x30})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:368 +0x43d
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).processNextWorkItem(0xc00014c240)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:324 +0xda
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).worker(0xc0005a66a0?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:313 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x1?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006fcc00?, {0x21f1be0, 0xc000af73e0}, 0x1, 0xc0001151a0)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2050160?, 0x3b9aca00, 0x0, 0x0?, 0xc0005a6710?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005a67d0?, 0x8cd9e6?, 0xc0005ce980?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x25
created by github.com/openshift/machine-config-operator/pkg/operator.(*Operator).Run
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:282 +0x67a
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 268 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000210070?})
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x1d70460, 0xc0020d6408})
	/usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/openshift/machine-config-operator/pkg/operator.getIgnitionHost(0xc0005bdca0)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:366 +0x4f9
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncRenderConfig(0xc00014c240, 0x4bcc17?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:336 +0xe28
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncAll(0xc00014c240, {0xc0035c1d08, 0x6, 0x0?})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:115 +0x3b8
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).sync(0xc00014c240, {0xc0004f4c30, 0x30})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:368 +0x43d
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).processNextWorkItem(0xc00014c240)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:324 +0xda
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).worker(0xc0005a66a0?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:313 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x1?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006fcc00?, {0x21f1be0, 0xc000af73e0}, 0x1, 0xc0001151a0)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2050160?, 0x3b9aca00, 0x0, 0x0?, 0xc0005a6710?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005a67d0?, 0x8cd9e6?, 0xc0005ce980?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x25
created by github.com/openshift/machine-config-operator/pkg/operator.(*Operator).Run
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:282 +0x67a
```

</details>

Issue appears to be that the `workers` array is empty:
https://github.com/openshift/machine-config-operator/blob/release-4.12/pkg/operator/operator.go#L281:L282

Not sure how that's happening:

<details>
  <summary>Nodes and MachineConfigPools</summary>

```
$ oc get node
NAME    STATUS   ROLES    AGE   VERSION
games   Ready    worker   14d   v1.24.6+5658434
mf0     Ready    worker   98d   v1.24.6+5658434
mf1     Ready    worker   13d   v1.24.6+5658434
mf2     Ready    worker   15d   v1.24.6+5658434
mf3     Ready    worker   90d   v1.24.6+5658434
mf4     Ready    worker   90d   v1.24.6+5658434
nuc1    Ready    master   85d   v1.24.6+5658434
nuc2    Ready    master   85d   v1.24.6+5658434
nuc3    Ready    master   90d   v1.24.6+5658434
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-035a083f2003fb81e8a7b7af2db85e98   True      False      False      3              3                   3                     0                      257d
worker   rendered-worker-b65d1bc0b7d428389f8432fade4acdef   True      False      False      6              6                   6                     0                      257d
```

</details>

**Version**
Last completed version was 4.11.0-0.okd-2022-12-02-145640
Currently attempting to upgrade to 4.12.0-0.okd-2023-01-21-055900
Cluster is on bare metal and was originally installed via assisted-service in 4.10 and later stripped of BareMetalHosts - I suspect this is related, since I can't imagine sane people doing this and nobody else is having this issue.

**How reproducible**
Pod is consistently crashlooping at the moment.

**Log bundle**
https://chat.jharmison.com/files/1boybor913bijq6979oi55j3zr/public?h=Zk-GQUwT5zYeqQ3ToTf8raLjQowYifzMj4Rl3dos3Z4

**Comment by solacelost** [comment]
Tried to force an upgrade to 4.12.0-0.okd-2022-02-04-212953 hoping blindly that there was some change in machine-config-operator that might have fixed this that didn't jump out at me from the changelog.

MCO is exhibiting the exact same behavior:

<details>
  <summary>Cluster Settings Details page</summary>

![image](https://user-images.githubusercontent.com/25357255/218109812-3f17b5a2-20ad-420e-b97c-e1f9218d4ee4.png)

</details>

<details>
  <summary>MCO logs</summary>

```
I0210 13:56:24.194240       1 start.go:47] Version: 4.12.0-0.okd-2023-02-04-212953 (Raw: machine-config-daemon-4.6.0-202006240615.p0-1787-g84e78c83-dirty, Hash: 84e78c83d5f1d6cb97a43b264154f1f519b69fb2)
I0210 13:56:24.200244       1 leaderelection.go:248] attempting to acquire leader lease openshift-machine-config-operator/machine-config...
I0210 13:58:57.132139       1 leaderelection.go:258] successfully acquired lease openshift-machine-config-operator/machine-config
I0210 13:58:57.955291       1 operator.go:276] Starting MachineConfigOperator
E0210 13:58:57.996066       1 runtime.go:79] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 270 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d52220?, 0xc004db4480})
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0001179d0?})
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1d52220, 0xc004db4480})
	/usr/lib/golang/src/runtime/panic.go:884 +0x212
github.com/openshift/machine-config-operator/pkg/operator.getIgnitionHost(0xc00016eaa0)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:366 +0x4ff
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncRenderConfig(0xc0003a8240, 0x4c1017?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:336 +0xe5e
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncAll(0xc0003a8240, {0xc004cb9d08, 0x6, 0x44b9d6?})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:115 +0x3b8
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).sync(0xc0003a8240, {0xc000b88630, 0x30})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:368 +0x43d
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).processNextWorkItem(0xc0003a8240)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:324 +0xda
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).worker(0xc0006deea0?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:313 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x21d4700, 0xc00116d3b0}, 0x1, 0xc000748660)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006defb0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x8bf58a?, 0x0?, 0x0?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x25
created by github.com/openshift/machine-config-operator/pkg/operator.(*Operator).Run
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:282 +0x67c
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 270 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0001179d0?})
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1d52220, 0xc004db4480})
	/usr/lib/golang/src/runtime/panic.go:884 +0x212
github.com/openshift/machine-config-operator/pkg/operator.getIgnitionHost(0xc00016eaa0)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:366 +0x4ff
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncRenderConfig(0xc0003a8240, 0x4c1017?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:336 +0xe5e
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).syncAll(0xc0003a8240, {0xc004cb9d08, 0x6, 0x44b9d6?})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/sync.go:115 +0x3b8
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).sync(0xc0003a8240, {0xc000b88630, 0x30})
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:368 +0x43d
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).processNextWorkItem(0xc0003a8240)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:324 +0xda
github.com/openshift/machine-config-operator/pkg/operator.(*Operator).worker(0xc0006deea0?)
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:313 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x21d4700, 0xc00116d3b0}, 0x1, 0xc000748660)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006defb0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x8bf58a?, 0x0?, 0x0?)
	/go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x25
created by github.com/openshift/machine-config-operator/pkg/operator.(*Operator).Run
	/go/src/github.com/openshift/machine-config-operator/pkg/operator/operator.go:282 +0x67c
```

</details>

**Comment by kalik1** [comment]
Hi @solacelost,
    watcing the code, I don't think is related to `workers `, array as you can see `[here](https://github.com/openshift/machine-config-operator/blob/1fab7126698c52ba8e56ab1267b7aa3e7ab3e657/pkg/operator/operator.go#L229)`, it is defined as an `int`eger value.

Watching the stacktrace, i think it is realted to this line of [/pkg/operator/sync.go](https://github.com/openshift/machine-config-operator/blob/84e78c83d5f1d6cb97a43b264154f1f519b69fb2/pkg/operator/sync.go#L366) 

It looks that `apiServerInternalIP` is not set.... 

I don't have a baremetal cluster (I hope one day ♥), but I can share with you my oVirt config: 

![okd_cluster_info](https://user-images.githubusercontent.com/24699236/218218481-8a6b717f-5e20-48fd-aef3-e2b061c3d43b.png)

I think you could try going to Administration -> Cluster Settings -> Global Configuration -> Infrastructure -> YAML

and verify the section

```yaml
status:
  [... something else ...]
  platformStatus:
    baremetal:
      apiServerInternalIP: 192.168.1.20 <-- REPLACE
      ingressIP: 192.168.1.30 <-- REPLACE
```

If it doesn't work, you could try setting the array in this way:

```yaml
status:
  [... something else ...]
  platformStatus:
    baremetal:
      apiServerInternalIPs: 
         - 192.168.1.20 <-- REPLACE
      ingressIPs:
         -  192.168.1.30 <-- REPLACE
```

Note: i had only a 4.8 cluster ATM, but it should be the same as in 4.12.

Hope it helps, 
kalik1

**Comment by solacelost** [comment]
While it wasn't an issue with the IP, your pointer _was_ extremely helpful! I had previously, while removing my BareMetalHosts and converting my assisted-service BareMetal cluster to a more UPI-like cluster (with no `Provisioning` object and no metal3 deployment) set `.spec.platformSpec.type` to `None`. This caused some weirdness in the lookups in the status, as you linked in `sync.go`. I just set it back to `BareMetal` despite my frankencluster lacking `BareMetalHosts` and.... tada, she's coming up.

So - thanks for the better stack trace reading than mine!

**Comment by kalik1** [comment]
I'm happy it solved :) I edited my post because I just realized the IPs are in the `status` section and not in the `spec`...
